version: '3.0'
services:
  client:
    image: node:20.2-alpine3.17
    env_file:
      - .env
    container_name: ${COMPOSE_PROJECT_NAME}.todo-client
    ports:
      - ${PORT_HOST}:${PORT_CONTAINER}
    extra_hosts:
      - '0.0.0.0:0.0.0.0'
    volumes:
      - './app:/app'
    working_dir: /app
    tty: true
    command: ash -c "npm install && npm start"
    networks:
      dockernet: null

networks:
  dockernet:
    external:
      name: dockernet
